name: New Pull Request Alert

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      API_URL: "https://ctf.catch-the-frog.com"
    
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Debug Branch Info
      run: |
        echo "Base branch: ${{ github.event.pull_request.base.ref }}"
        echo "Head branch: ${{ github.event.pull_request.head.ref }}"
        echo "Workflow is running with the PR's head branch."

    - name: healthcheck
      continue-on-error: true
      env:
        URL: ${{ env.API_URL }}
        USER: ${{ secrets.USER }}
        PW: ${{ secrets.USER_CRED }}
      run: |
        echo "Printing USER environment variable..."
        echo "USER=$USER"
        echo "Login health check from harry"
        curl --connect-timeout 2 -sSf -k -u "$USER:$PW" $URL/login
